### ISSUE TITLE
Mudar a cor dos ícones na ação "hover" dos botões de Apoio da Home 

### ISSUE THREAD

**Issue by FernandaBroch** [cloudgirlsin/ProjetoEfraim#23]
Essa é a imagem dos botões de Apoio da página home:
![image](https://user-images.githubusercontent.com/8379197/100774196-962aa480-33e0-11eb-8a97-776a6a0cc7c7.png)

**Problema**
Quando realizo a ação "hover" no botão, consigo mudar as cores da fonte e do background do botão, mas o ícone permanece com a mesma cor branca e acaba desaparecendo na ação:
![image](https://user-images.githubusercontent.com/8379197/100774413-ceca7e00-33e0-11eb-9032-5bdd73abb33b.png)

**Comment by primarinovic** [comment]
conseguimos mudar!
